<?php
return [
    'Acura' => 'default.png',
    'Audi' => 'audi.png',
    'BMW' => 'bmw.png',
    'Buick' => 'default.png',
    'Cadillac' => 'default.png',
    'Chevrolet' => 'chevrolet.png',
    'Chrysler' => 'default.png',
    'Dodge' => 'dodge.png',
    'Ford' => 'ford.png',
    'GMC' => 'gmc.png',
    'Honda' => 'honda.png',
    'Hyundai' => 'hyundai.png',
    'Infiniti' => 'default.png',
    'Jeep' => 'jeep.png',
    'Kia' => 'kia.png',
    'Lexus' => 'default.png',
    'Lincoln' => 'default.png',
    'Mazda' => 'mazda.png',
    'Mercedes-Benz' => 'mercedes-benz.png',
    'Mitsubishi' => 'mitsubishi.png',
    'Nissan' => 'nissan.png',
    'Ram' => 'ram.png',
    'Subaru' => 'subaru.png',
    'Tesla' => 'default.png',
    'Toyota' => 'toyota.png',
    'Volkswagen' => 'volkswagen.png',
    'Volvo' => 'volvo.png',
];
